---

- name: install
  remote_user: "{{ ansible_user }}"
  hosts: "{{ group }}"
  vars:
      programming: false
      group: localhost
  roles:
      - bash
      - vim
      - fish
      - zsh
      - byobu
