---

- name: Install sdcv package
  apt: name={{ item }} state=present
  with_items:
   - sdcv
  become: true

- copy: src={{ item }} dest="/dev/shm/{{ item }}"
  with_items:
   - stardict-dictd_www.dict.org_gcide-2.4.2.tar
   - stardict-dictd_www.dict.org_wn-2.4.2.tar
   - stardict-langdao-ce-big5-2.4.2.tar
   - stardict-oald-2.4.2.tar
   - stardict-oxford_collocations-2.4.2.tar

- file: path='~/.stardict/dic' state=directory mode=0755

- unarchive: src={{ item }}
             dest=~/.stardict/dic
  with_items:
   - stardict-dictd_www.dict.org_gcide-2.4.2.tar
   - stardict-dictd_www.dict.org_wn-2.4.2.tar
   - stardict-langdao-ce-big5-2.4.2.tar
   - stardict-oald-2.4.2.tar
   - stardict-oxford_collocations-2.4.2.tar
