- name: download fish source code
  get_url: url="{{ fish_download_url }}" dest=/tmp/fish.tar.gz mode=0440

- unarchive: src=/tmp/fish.tar.gz
             dest=/tmp/

- name: generate fish configure
  command: "{{ item }}"
  args:
    chdir: "/tmp/fish-{{ fish_version }}"
    creates: "/tmp/fish-{{ fish_version }}/configure"
  with_items:
    - autoconf

- name: generate fish Makefile
  command: "{{ item }}"
  args:
    chdir: "/tmp/fish-{{ fish_version }}"
    creates: "/tmp/fish-{{ fish_version }}/Makefile"
  with_items:
    - "./configure"

- name: build fish
  command: "{{ item }}"
  args:
    chdir: "/tmp/fish-{{ fish_version }}"
  with_items:
    - make

- name: install fish
  command: "{{ item }}"
  args:
    chdir: "/tmp/fish-{{ fish_version }}"
  with_items:
    - "make install"
  become: true


