---

- name: Install fish dependent package
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - ncurses-dev
    - libncurses5-dev
    - gettext
    - autoconf
  sudo: yes
  when: ansible_distribution == 'Ubuntu'

- name: Install fish dependent package
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - ncurses-dev
    - libncurses5-dev
    - gettext
    - autoconf
  sudo: yes
  when: ansible_distribution == 'Debian'

- name: Install fish dependent package
  dnf: name={{ item }} state=present
  with_items:
    - ncurses-devel
  sudo: yes
  when: ansible_distribution == 'Fedora'

- name: download fish source code
  get_url: url="{{ fish_download_url }}" dest=/tmp/fish.tar.gz mode=0440

- unarchive: src=/tmp/fish.tar.gz
             dest=/tmp/

- name: generate fish configure
  command: "{{ item }}"
  args:
    chdir: "/tmp/fish-{{ fish_version }}"
  with_items:
    - autoconf

- name: generate fish Makefile
  command: "{{ item }}"
  args:
    chdir: "/tmp/fish-{{ fish_version }}"
  with_items:
    - "./configure"

- name: build fish
  command: "{{ item }}"
  args:
    chdir: "/tmp/fish-{{ fish_version }}"
  with_items:
    - make

- name: install fish
  command: "{{ item }}"
  args:
    chdir: "/tmp/fish-{{ fish_version }}"
  with_items:
    - "make install"
  sudo: yes

- name: install oh-my-fish
  git: repo=https://github.com/oh-my-fish/oh-my-fish.git
       dest="~/.local/share/omf"

- name: install virtualenv helper for fish
  pip: name=virtualfish
  sudo: yes

