---
- name: Install bash-completion package
  apt: name={{ item }} state=present
  with_items:
   - bash-completion
  sudo: yes
  when: ansible_distribution == 'Ubuntu'

- name: Install bash-completion package
  dnf: name={{ item }} state=present
  with_items:
   - bash-completion
  sudo: yes
  when: ansible_distribution == 'Fedora'

- git: repo=https://github.com/magicmonty/bash-git-prompt.git
       dest=~/.bash-git-prompt
       depth=1

- git: repo=https://github.com/nojhan/liquidprompt
       dest=~/.liquidprompt
       depth=1
