---
- name: Install bash-completion package
  apt: name={{ item }} state=present
  with_items:
   - git
  sudo: yes
  when: ansible_distribution == 'Ubuntu'

- name: Install bash-completion package
  dnf: name={{ item }} state=present
  with_items:
   - bash-completion
   - git
  sudo: yes
  when: ansible_distribution == 'Fedora'

- git: repo=https://github.com/Bash-it/bash-it.git
       dest="~/.bash_it"
       depth=1

- shell: "~/.bash_it/install.sh"
  ignore_errors: yes
