---

- file: path=~/mybin state=directory

- copy: src="{{ item }}"
        dest="~/mybin/{{ (item|splitext)[0] }}"
        mode=0755
  with_items:
      - asyn
      - copy.sh
      - init_sbt.py
      - paste.sh
      - p.py
      - send_key.py
      - set_cpu_governor.py
      - to_ebook.sh
      - to_mobi.sh
      - to_utf8.py
      - use_ssh_for_github.py
      - ydict.sh
      - dw.py
      - cmd.py
      - aboot_x86_64.sh
      - boot_x86_64.sh
      - aboot_x86.sh
      - boot_x86.sh
      - create_qcow2.sh
      - del_qcow2_dev.sh
      - mk_qcow2_dev.sh
      - mount_qcow2.sh
      - show_qcow2_partitions.sh
      - vagrant-init.py
      - hterm-copy.sh
      - hterm-notify.sh
      - port-foreward


- lineinfile: dest=~/.zshrc line="export PATH=\"`pwd`/mybin/:$PATH\""
  ignore_errors: yes

- lineinfile: dest=~/.bashrc line="export PATH=\"`pwd`/mybin/:$PATH\""
  ignore_errors: yes
