---

- file: path=~/mybin state=directory

- name: copy mybin
  copy: src="mybin/"
        dest="~/mybin/"
        mode=0755

- lineinfile: dest=~/.zshrc line="export PATH=\"`pwd`/mybin/:$PATH\""
  ignore_errors: yes

- lineinfile: dest=~/.bashrc line="export PATH=\"`pwd`/mybin/:$PATH\""
  ignore_errors: yes
