#! /bin/bash

dnf install python-pip python-devel git vim python-dnfdaemon python-dnf-plugins-core redhat-rpm-config libselinux-python gcc-c++
dnf groupinstall "Development Tools"
dnf builddep ansible
pip install ansible
