---

- name: install
  remote_user: "{{ ansible_user }}"
  hosts: "{{ group }}"
  vars:
      programming: false

  roles:
      - bash-it
      - vim
      - fish
      - zsh
      - byobu
      - fish
