---

- name: install
  remote_user: "{{ ansible_user }}"
  hosts: "{{ group }}"

  roles:
      - activator
      - atom
      - bash
      - common-packages
      - desktop-packages
      - developer-packages
      - docker
      - i3
      - mybin
      - sbt
      - sdcv
      - vim
      - xbindkeys
      - zsh
