#!/bin/bash
if [ -f `which nvr` ] && [ $# -ne 0 ] && [ -f /tmp/nvimsocket  ]; then
  nvr $@
elif [ -f `which nvim` ]; then
    nvim $@
elif [ -f /usr/local/bin/vim ]; then
    /usr/local/bin/vim $@
elif [ -f /usr/bin/vim ]; then
    /usr/bin/vim $@
else
  echo "No vim found"
fi
