#!/bin/bash
random-color-scheme.py
if [ -f `which nvr` ] && [ $# -ne 0 ] && [ -f /tmp/nvimsocket  ]; then
  nvr $@
elif [ -f `which nvim` ]; then
    if [ -z ${IN_VIM+x} ]; then
      tmux rename-window nvim
      nvim $@
    else
      myvi $@
    fi
elif [ -f /usr/local/bin/vim ]; then
    /usr/local/bin/vim $@
elif [ -f /usr/bin/vim ]; then
    /usr/bin/vim $@
else
  echo "No vim found"
fi
