---

- name: Install virtualbox guest package
  apt: name={{ item }} state=present
  with_items:
      - virtualbox-guest-dkms
      - virtualbox-guest-utils
      - virtualbox-guest-x11
  become: true
