#!/usr/bin/bash
rofi -modi 'combi,bookmark:bookmarks.py,search:search.py' -show combi \
  -combi-modi search,window,bookmark,ssh,drun -kb-mode-next 'Alt-l' \
  -kb-row-up 'Alt-p' -kb-row-down 'Alt-n' -no-disable-history
