#!/usr/bin/bash
rofi -modi 'combi,bookmark:bookmarks.py,search:search.py,dirs:rofi-dirs' -show combi \
  -combi-modi search,window,bookmark,dirs,ssh,drun -kb-mode-next 'Alt-l' \
  -kb-row-up 'Alt-k' -kb-row-down 'Alt-j' -no-disable-history \
  -theme Arc-Dark -font 'mono 15'

