---

- apt: name={{ item }} state=present
  with_items:
   - xbindkeys
   - xvkbd
  sudo: yes

- pip: name={{ item }}
  with_items:
      - psutil
  sudo: yes

- copy: src="send_key.py"
        dest="~/send_key.py"
        mode="u+x"
