---
- name: Remove openssh-server
  apt: name={{ item }} state=absent
  with_items:
    - openssh-server
  sudo: yes

- name: Install openssh-server
  apt: name={{ item }} state=present
  with_items:
    - openssh-server
  sudo: yes
