---

- name: create .vifm
  file: path="~/.vifm" state=directory mode=0755

- name: copy vifmrc
  template: src=vifmrc dest="~/.vifm/vifmrc"

- name: copy editit script
  copy: src="editit.py" dest="~/.vifm/editit.py"
