---

- name: Install vifm package
  apt: name={{ item }} state=present
  with_items:
   - byobu
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Install vifm package
  apt: name={{ item }} state=present
  with_items:
   - byobu
  become: true
  when: ansible_distribution == 'Debian'
