---

- name: Install byobu package
  apt: name={{ item }} state=present
  with_items:
   - byobu
  become: true
  when: ansible_distribution == 'Ubuntu' or ansible_os_family == "\"elementary\""

- name: Install byobu package
  dnf: name={{ item }} state=present
  with_items:
   - byobu
  become: true
  when: ansible_distribution == 'Fedora'

- name: Install byobu package
  yum: name={{ item }} state=present
  with_items:
   - byobu
  become: true
  when: ansible_distribution == 'CentOS'
