---
- name: Update env.nu
  blockinfile:
    path: ~/.config/nushell/env.nu
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      let-env PATH = ($env.PATH | prepend {{ NUSHELL_EXTRA_PATH }})

- name: Update config.nu
  blockinfile:
    path: ~/.config/nushell/config.nu
    marker: "# {mark} ANSIBLE MANAGED BLOCK - nushell config"
    block: |
      let-env config = ($env.config | upsert show_banner false)
      let-env config = ($env.config | upsert edit_mode vi)
      let-env EDITOR = nvim
      alias vim = nvim
      alias in = enter
      alias s = shells
      alias cd1 = cd ..
      alias cd2 = cd ../../
      alias cd3 = cd ../../../
      alias cd4 = cd ../../../../
      alias cd5 = cd ../../../../../
      alias z1 = cd ..
      alias z2 = cd ../../
      alias z3 = cd ../../../
      alias z4 = cd ../../../../
      alias z5 = cd ../../../../../
      let-env config.hooks.pre_prompt = ( $env.config.hooks.pre_prompt | append [{ ||
            let direnv = (direnv export json | from json)
            let direnv = if ($direnv | length) == 1 { $direnv } else { {} }
            $direnv | load-env
          }] )
      let-env config = ($env.config | merge {
        history: {
          file_format: "sqlite"
          history_isolation: false
          sync_on_enter: true
        }
        hooks: {
          env_change: {cloud: [
            { |before, after|
              if ( $env.cloud == 1 ) {
                  let-env PROMPT_COMMAND = { || create_left_prompt }
              } else {
                source ~/.oh-my-posh.nu
              }
            }
          ]}
      }})

      def update-z [ path ] {
        ls -f $path | where type == dir | par-each { |it|
          let name = (readlink -f $it.name)
          if (zoxide query $name | str contains $name ) {
            echo $"($name) exists"
          } else {
            zoxide add $name
            echo $"Adding ($name)"
          }
        }
      }

      let-env PROMPT_COMMAND = { ||
      let segment = ([
        (prompt --exit_code $env.LAST_EXIT_CODE --duration $env.CMD_DURATION_MS)
        "\n"
        ->
        ] |str join)
        $segment
      }
      let-env PROMPT_COMMAND_RIGHT = ""

      use ~/nu_scripts/modules/kubernetes/kubernetes.nu *
      use ~/nu_scripts/modules/git/git-v2.nu *
      use ~/nu_scripts/modules/network/ssh.nu *
      use ~/nu_scripts/modules/docker/docker.nu *
      use ~/nu_scripts/modules/nvim/nvim.nu *

      use std 'log debug'
      use std 'log info'
      use std 'log warning'
      use std 'log error'
      use std 'log critical'

      let-env config = ($env.config | upsert keybindings ( $env.config.keybindings | append [{ name: custom modifier: alt keycode: char_l mode: [emacs vi_normal vi_insert]  event: { until: [{ send: menu name: completion_menu } { send: menunext } ]} }] ))
      let-env config = ($env.config | upsert keybindings ( $env.config.keybindings | append [{ name: custom modifier: alt keycode: char_h mode: [emacs vi_normal vi_insert]  event: { send: menuprevious } }] ))
      let-env config = ($env.config | upsert keybindings ( $env.config.keybindings | append [{ name: custom modifier:alt keycode: char_j mode: [emacs vi_normal vi_insert]  event: { send: down } }] ))
      let-env config = ($env.config | upsert keybindings ( $env.config.keybindings | append [{ name: custom modifier:alt keycode: char_k mode: [emacs vi_normal vi_insert]  event: { send: up } }] ))
      let-env config = ($env.config | upsert keybindings ( $env.config.keybindings | append [{ name: custom modifier:control keycode: char_f mode: [emacs vi_normal vi_insert]  event: { send: HistoryHintComplete } }] ))
      let-env config = ($env.config | upsert keybindings ( $env.config.keybindings | append [{ name: custom modifier:alt keycode: char_f mode: [emacs vi_normal vi_insert]  event: { send: HistoryHintWordComplete } }] ))


- name: Check if starship exists
  shell: which starship
  register: starship_result

- name: Render config if starship exists
  blockinfile:
    path: ~/.config/nushell/config.nu
    marker: "# {mark} ANSIBLE MANAGED BLOCK - starship"
    block: |
      def create_left_prompt [] {
          starship prompt --cmd-duration $env.CMD_DURATION_MS $'--status=($env.LAST_EXIT_CODE)'
      }
  when: starship_result.rc == 0

- name: Check if file exists
  stat:
    path: ~/.oh-my-posh.nu
  register: file_status


- name: Update config.nu
  blockinfile:
    path: ~/.config/nushell/config.nu
    marker: "# {mark} ANSIBLE MANAGED BLOCK - oh-my-posh"
    block: |
      source ~/.oh-my-posh.nu
  when: file_status.stat.exists and starship_result.rc > 0
