---
- name: Update env.nu
  blockinfile:
    path: ~/.config/nushell/env.nu
    marker: "# {mark} ANSIBLE MANAGED BLOCK PATH"
    block: |
      $env.PATH = ($env.PATH | prepend {{ NUSHELL_EXTRA_PATH }})

- name: Update config.nu
  blockinfile:
    path: ~/.config/nushell/config.nu
    marker: "# {mark} ANSIBLE MANAGED BLOCK - nushell {{ item }}"
    block: "{{ lookup('ansible.builtin.file', item) }}"
  with_items:
    - config.nu
    - clipboard.nu
    - pueue.nu

- name: Check if starship exists
  shell: which starship
  register: starship_result
  ignore_errors: true

- name: Render config if starship exists
  blockinfile:
    path: ~/.config/nushell/config.nu
    marker: "# {mark} ANSIBLE MANAGED BLOCK - starship"
    block: |
      def create_left_prompt [] {
          starship prompt --cmd-duration $env.CMD_DURATION_MS $'--status=($env.LAST_EXIT_CODE)'
      }
  when: starship_result.rc == 0

- name: Check if file exists
  stat:
    path: ~/.oh-my-posh.nu
  register: file_status

- name: Update config.nu
  blockinfile:
    path: ~/.config/nushell/config.nu
    marker: "# {mark} ANSIBLE MANAGED BLOCK - oh-my-posh"
    block: |
      source ~/.oh-my-posh.nu
  when: file_status.stat.exists and starship_result.rc > 0

- name: Check if nu_scripts exists
  stat:
    path: ~/nu_scripts/
  register: file_status

- name: Update config.nu
  blockinfile:
    path: ~/.config/nushell/config.nu
    marker: "# {mark} ANSIBLE MANAGED BLOCK - modules"
    block: |
      use ~/nu_scripts/modules/kubernetes/kubernetes.nu *
      use ~/nu_scripts/modules/git/git-v2.nu *
      use ~/nu_scripts/modules/network/ssh.nu *
      use ~/nu_scripts/modules/docker/docker.nu *
      use ~/nu_scripts/modules/nvim/nvim.nu *
      use ~/nu_scripts/modules/after/after.nu *
  when: file_status.stat.exists
