---
- name: Update env.nu
  blockinfile:
    path: ~/.config/nushell/env.nu
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      let-env PATH = ($env.PATH | prepend {{ NUSHELL_EXTRA_PATH }})


- name: Update config.nu
  blockinfile:
    path: ~/.config/nushell/config.nu
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      let-env config = ($env.config | upsert show_banner false)
      alias vim = nvim
      source ~/.oh-my-posh.nu
      let-env config = ($env.config | upsert keybindings ( $env.config.keybindings | append [{ name: custom modifier: alt keycode: char_l mode: [emacs vi_normal vi_insert]  event: { until: [{ send: menu name: completion_menu } { send: menunext } ]} }] ))
      let-env config = ($env.config | upsert keybindings ( $env.config.keybindings | append [{ name: custom modifier: alt keycode: char_h mode: [emacs vi_normal vi_insert]  event: { send: menuprevious } }] ))
      let-env config = ($env.config | upsert keybindings ( $env.config.keybindings | append [{ name: custom modifier:alt keycode: char_j mode: [emacs vi_normal vi_insert]  event: { send: down } }] ))
      let-env config = ($env.config | upsert keybindings ( $env.config.keybindings | append [{ name: custom modifier:alt keycode: char_k mode: [emacs vi_normal vi_insert]  event: { send: up } }] ))
