- name: Get the latest pueue version
  ansible.builtin.uri:
    url: "https://api.github.com/repos/nushell/nushell/releases/latest"
    return_content: yes
  register: json_data

- name: Get the latest version of the nushell
  set_fact:
    nushell_version: "{{ json_data['json'] | json_query('tag_name') }}"

- name: Download the latest version of the nushell
  ansible.builtin.unarchive:
    src: "https://github.com/nushell/nushell/releases/download/{{ nushell_version }}/nu-{{ nushell_version}}-x86_64-unknown-linux-musl.tar.gz"
    dest: /tmp
    remote_src: yes
    extra_opts:
      - "--strip-components=1"

- name: Move the nushell binary to /usr/local/bin
  ansible.builtin.copy:
    src: /tmp/nu
    dest: /usr/bin/nu
    mode: 0755
  become: true


