---
- include: "install-debian.yml"
  when: ansible_distribution == 'Debian'

- include: "install-ubuntu.yml"
  when: ansible_distribution == 'Ubuntu' or ansible_os_family == "\"elementary\""

- include: "install-fedora.yml"
  when: ansible_distribution == 'Fedora'

- include: "install-centos.yml"
  when: ansible_distribution == 'CentOS'

- include: "install-osx.yml"
  when: ansible_distribution == 'MacOSX'

