---

- name: download activator.zip
  get_url: url={{ activator_url }} dest=/tmp/activator.zip validate_certs=False


- name: unzip activator.zip
  unarchive: src=/tmp/activator.zip dest=~/

- name: rename from activator-version to activator
  command: mv ~/activator-{{ activator_version }}-minimal ~/activator
  args:
    creates: "~/activator"

- name: remove from activator-version to activator
  command: rm -rf ~/activator-{{ activator_version }}-minimal
