---
- copy: src="i3-config" dest="~/"
- command: "rm -rf ~/.i3"
  ignore_errors: True
- command: "mv ~/i3-config ~/.i3"

- file: path=~/.i3/{{ item }} mode=u+x
  with_items:
      - auto_config_resolution.py
      - focus_screen.py
      - go_to_window.py
      - i3.py
      - lib.py
      - move_container_left.py
      - move_container.py
      - move_container_right.py
      - move_workspace_left.py
      - move_workspace_right.py
      - quick_switch.py
      - show_output_workspace.py
      - show_tiling_window_from_scratchpad.py
      - show_weather.py
      - swap.py
      - swap_workspace_with_current.py
      - switch.py
      - dual_screen.sh
      - rename_worksapce.sh
      - run_xfce4_panel.sh
      - swap_workspace.sh
      - i3exit
      - new_screen_in.py
      - quick_insert.py
      - choose_window_in_scratchpad.py
      - go_to_mark.py
      - run_lxpanel.sh
      - new_quick_switch.py
      - name_workspace.py
      - i3_switch_workspace.sh
      - create_workspace.py
      - noteit.py
      - show_workspace_info.py
      - insert_from_fish_history.py

- command: "mkdir -p ~/.config/touchegg/"
  args:
      creates: "~/.config/touchegg"

- copy: src="touchegg.conf" dest="~/.config/touchegg/"

- file: path="~/.config/lxterminal" state=directory mode=0755

- copy: src="lxterminal.conf" dest="~/.config/lxterminal/"

- file: path="~/.config" state=directory mode=0755

- file: path="~/.config/lxpanel" state=directory mode=0755

- copy: src="jelly" dest="~/.config/lxpanel/"

- file: src=~/.i3/i3.py dest=~/.i3/modules/i3.py state=link

- file: path="~/.config/xfce4/terminal" state=directory mode=0755

- copy: src="terminalrc" dest="~/.config/xfce4/terminal/"

- file: path="~/bin" state=directory mode=0755

- copy: src="ir" dest="~/bin/ir" mode=0755

- copy: src="ivi" dest="~/bin/ivi" mode=0755

- copy: src="vim" dest="~/bin/vim" mode=0755

- copy: src="vim" dest="~/bin/vim" mode=0755

- copy: src="xinputrc" dest="~/.xinputrc"

- file: path="~/.config/fcitx/" state=directory mode=0755

- copy: src="fcitx_config" dest="~/.config/fcitx/"
