---
- copy: src="i3-config" dest="~/"
- command: "rm -rf ~/.i3"
  ignore_errors: True
- command: "mv ~/i3-config ~/.i3"

- copy: src="Xmodmap" dest="~/"
- command: "rm -rf ~/.Xmodmap"
  ignore_errors: True
- command: "mv ~/Xmodmap ~/.Xmodmap"

- file: path=~/.i3/{{ item }} mode=u+x
  with_items:
      - auto_config_resolution.py
      - focus_screen.py
      - go_to_window.py
      - i3.py
      - lib.py
      - move_container_left.py
      - move_container.py
      - move_container_right.py
      - move_workspace_left.py
      - move_workspace_right.py
      - quick_switch.py
      - show_output_workspace.py
      - show_tiling_window_from_scratchpad.py
      - show_weather.py
      - swap.py
      - swap_workspace_with_current.py
      - switch.py
      - dual_screen.sh
      - rename_worksapce.sh
      - run_xfce4_panel.sh
      - swap_workspace.sh
      - i3exit
      - new_screen_in.py
      - quick_insert.py
      - choose_window_in_scratchpad.py
      - go_to_mark.py
      - run_lxpanel.sh
      - new_quick_switch.py

- command: "mkdir -p ~/.config/touchegg/"
  args:
      creates: "~/.config/touchegg"

- copy: src="touchegg.conf" dest="~/.config/touchegg/"

- file: path="~/.config/lxterminal" state=directory mode=0755

- copy: src="lxterminal.conf" dest="~/.config/lxterminal/"

- file: path="~/.config" state=directory mode=0755

- file: path="~/.config/lxpanel" state=directory mode=0755

- copy: src="jelly" dest="~/.config/lxpanel/"
