---
- name: Remove some useless package(i3 role)
  apt: name={{ item }} state=absent
  with_items:
      - ibus
      - ibus-chewing
      - hime
      - hime-chewing
  when: ansible_os_family == 'Debian'
  ignore_errors: yes
- name: Install i3 dependence lib
  apt: name={{ item }} state=present
  with_items:
    - "libxcb1-dev"
    - "libxcb-keysyms1-dev"
    - "libxcb-util0-dev"
    - "libxcb-icccm4-dev"
    - "libyajl-dev"
    - "libstartup-notification0-dev"
    - "libxcb-randr0-dev"
    - "libev-dev"
    - "libxcb-xinerama0-dev"
    - "libpango1.0-dev"
    - "libxcursor-dev"
    - "libxcb-xkb-dev"
    - "libxcb-cursor-dev"
    - "libxkbcommon-x11-dev"
    - "libxkbcommon-dev"
    - "build-essential"
    - "freeglut3-dev"
    - "libfreeimage-dev"
    - "libgl1-mesa-dev"
    - "libopenal-dev"
    - "libsdl-ttf2.0-dev"
    - "libsndfile-dev"
    - "libxinerama-dev"

  sudo: yes
  when: ansible_os_family == 'Debian'
  ignore_errors: yes

- name: Install i3 dependence lib for fedora
  dnf: name={{ item }} state=present
  with_items:
    - "spice-glib-devel"
    - "pango-devel"
    - "startup-notification-devel"

    - "libxcb-xinerama0-dev"
    - "libpango1.0-dev"
    - "libxcursor-dev"
    - "libxcb-xkb-dev"
    - "libxcb-cursor-dev"
    - "libxkbcommon-x11-dev"
    - "libxkbcommon-dev"
    - "build-essential"
    - "freeglut3-dev"
    - "libfreeimage-dev"
    - "libgl1-mesa-dev"
    - "libopenal-dev"
    - "libsdl-ttf2.0-dev"
    - "libsndfile-dev"
    - "libxinerama-dev"

  sudo: yes
  when: ansible_distribution == 'Fedora'
  ignore_errors: yes

- name: Install i3 package
  apt: name={{ item }} state=present
  with_items:
      - i3
      - i3status
      - terminator
      - python-pip
      - xfce4-panel
      - gnome-control-center
      - xbacklight
      - feh
      - touchegg
      - lm-sensors
      - lxterminal
      - lxpanel
      - xdotool
      - rofi
      - volti

      - boxes
      - libnotify-bin
      - zenity
      - toilet
      - whiptail
      - xfce4-screenshooter
      - xfce4-terminal

      - dunst
      - fcitx-chewing
      - fcitx-configtool

      - gnome-do # app launcher
      - kupfer # app launcher



  sudo: yes
  when: ansible_distribution == 'Ubuntu'

- name: Install i3 package
  apt: name={{ item }} state=present
  with_items:
      - i3
      - i3status
      - terminator
      - python-pip
      - xfce4-panel
      - gnome-control-center
      - xbacklight
      - feh
      - lm-sensors
      - lxterminal
      - lxpanel
      - xdotool
      - volti

      - boxes
      - libnotify-bin
      - zenity
      - toilet
      - whiptail
      - xfce4-screenshooter
      - xfce4-terminal

      - dunst
      - pkg-config
      - libgtk-3-dev
      - libstartup-notification0-dev

      - fcitx-chewing
  sudo: yes
  when: ansible_distribution == 'Debian'

- name: Install i3 package for fedora
  dnf: name={{ item }} state=present
  with_items:
      - i3
      - i3status
      - terminator
      - python-pip
      - xfce4-panel
      - xbacklight
      - feh
      - lxterminal
      - lxpanel
      - xdotool

      - boxes
      - zenity
      - xfce4-screenshooter
      - xfce4-terminal

      - dunst

      - fcitx-chewing
  sudo: yes
  when: ansible_distribution == 'Fedora'

- name: Install zsh package
  dnf: name={{ item }} state=present
  with_items:
   - i3
   - libX11-devel
   - libXext-devel
   - libXinerama-devel
   - libXft-devel
   - dmenu
   - lxterminal
   - i3status
   - conky
  sudo: yes
  when: ansible_distribution == 'Fedora'

- name: remove useless package for i3
  apt: name={{ item }} state=absent
  with_items:
    - xfce4-notifyd
    - notify-osd
  ignore_errors: yes
  when: ansible_distribution == 'Ubuntu'
  ignore_errors: yes

- name: Install python package for i3
  pip: name={{ item }}
  with_items:
      - i3-py
      - quickswitch-i3
      - py3status
  sudo: yes

- name: download dmenu  source code
  get_url: url="{{ dmenu_download_url }}" dest=/tmp/dmenu.tar.gz mode=0440

- unarchive: src=/tmp/dmenu.tar.gz
             dest=/tmp/

- name: change dmenu font
  lineinfile: dest=/tmp/dmenu-{{ dmenu_version }}/config.def.h
              regexp='"monospace:size=10"' state=present
              line='"monospace:size=19"'

- name: change dmenu font
  lineinfile: dest=/tmp/dmenu-{{ dmenu_version }}/config.mk
              regexp="\$\{X11INC\}/freetype2"
              state=absent

- name: build and install dmenu
  command: "{{ item }}"
  args:
    chdir: "/tmp/dmenu-{{ dmenu_version }}"
  with_items:
    - make
    - "make install"
  sudo: yes

- name: download rofi source code
  get_url: url="{{ rofi_download_url }}" dest=/tmp/rofi.tar.gz mode=0440

- unarchive: src=/tmp/rofi.tar.gz
             dest=/tmp/

- name: build rofi
  command: "{{ item }}"
  args:
    chdir: "/tmp/rofi-{{ rofi_version }}"
  with_items:
    - "./configure"
    - make

- name: install rofi
  command: "{{ item }}"
  args:
    chdir: "/tmp/rofi-{{ rofi_version }}"
  with_items:
    - "make install"
  sudo: yes
