---

- include: "install_debian_family.yml"
  when: ansible_distribution == 'Ubuntu' or ansible_os_family == "\"elementary\""

- include: "install_debian_family.yml"
  when: ansible_distribution == 'Fedora'

- name: apm install
  shell: apm install {{ item }}
  with_lines:
      - "cat roles/atom/files/base_package_list"
      - "cat roles/atom/files/advanced_package_list"

- copy: src="config.cson" dest="~/.atom/config.cson"
- copy: src="keymap.cson" dest="~/.atom/keymap.cson"
- copy: src="styles.less" dest="~/.atom/styles.less"
