---

- block:
    - name: download atom package
      get_url: url=https://atom.io/download/deb dest=/tmp/deb
      when: ansible_distribution == 'Ubuntu'

  rescue:
    - shell: wget https://atom.io/download/deb
      args:
          chdir: /tmp
      when: ansible_distribution == 'Ubuntu'
  always:
    - apt: deb=/tmp/deb
      sudo: yes



- name: apm install
  shell: apm install {{ item }}
  with_items:
      - language-scala
      - autocomplete-plus
      - scala-format
      - scala-worksheet
      - vim-mode
      - autocomplete
      - atom-beautify
- copy: src="config.cson" dest="~/.atom/config.cson"
- copy: src="keymap.cson" dest="~/.atom/keymap.cson"
