---

- block:
    - name: download atom package by get_url
      get_url: url=https://atom.io/download/deb dest=/tmp/deb

  rescue:
    - name: download atom package by wget
      shell: wget https://atom.io/download/deb
      args:
          chdir: /tmp
  always:
    - name: instalal atom from deb file
      apt: deb=/tmp/deb
      become: yes

- name: install package
  apt: name="{{ item }}" state=present
  with_items:
    - "silversearcher-ag"
  when: ansible_distribution == 'Ubuntu'
  become: yes
