---

- block:
    - name: download atom package
      get_url: url=https://atom.io/download/deb dest=/tmp/deb
      when: ansible_distribution == 'Ubuntu'

  rescue:
    - shell: wget https://atom.io/download/deb
      args:
          chdir: /tmp
      when: ansible_distribution == 'Ubuntu'
  always:
    - apt: deb=/tmp/deb
      sudo: yes

- name: install package
  apt: name="{{ item }}" state=present
  with_items:
    - "silversearcher-ag"
  when: ansible_distribution == 'Ubuntu'
  sudo: yes

- name: apm install
  shell: apm install {{ item }}
  with_items:
      - language-scala
      - autocomplete-plus
      - scala-format
      - vim-mode
      - "ex-mode"
      - "atom-fuzzy-grep"
      - autocomplete
      - atom-beautify
      - symbols-tree-view

- copy: src="config.cson" dest="~/.atom/config.cson"
- copy: src="keymap.cson" dest="~/.atom/keymap.cson"
- copy: src="styles.less" dest="~/.atom/styles.less"
