- name: Create ~/bin
  ansible.builtin.file:
    path: ~/bin/
    state: directory
    mode: 0755

- name: Copy p.py
  ansible.builtin.copy:
    src: p.py
    dest: "~/bin/{{ item }}"
    mode: 0755
  with_items:
    - p
    - job
