---
- name: Get the latest pueue version
  ansible.builtin.uri:
    url: "https://api.github.com/repos/Nukesor/pueue/releases/latest"
    return_content: yes
  register: json_data

- name: Get pueue version
  ansible.builtin.set_fact:
    pueue_version: "{{ json_data['json'] | json_query('tag_name') }}"
- name: Download pueue
  ansible.builtin.get_url:
    url: "https://github.com/Nukesor/pueue/releases/download/{{ pueue_version }}/{{ item }}-linux-x86_64"
    dest: "/bin/{{ item }}"
    mode: 0755
  become: true
  with_items:
    - pueue
    - pueued

- name: Copy systemd config
  ansible.builtin.template:
    src: "pueued.service"
    dest: "/etc/systemd/user/pueued.service"
    mode: "0664"
  become: true

- name: Start systemd
  ansible.builtin.systemd:
    name: pueued
    scope: user
    enabled: true
