---
- name: Copy tmux.conf
  ansible.builtin.copy:
    src: "tmux.conf"
    dest: "~/.tmux.conf"
    mode: "0600"

- name: Create ~/bin
  ansible.builtin.file:
    path: ~/bin
    state: directory
    mode: "0755"

- name: Copy binary
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "~/bin/{{ item | basename }}"
    mode: 0755
  with_fileglob:
    - "*"
  when: (item | basename) != 'tmux.conf'
