---
- name: Install package
  apt: name={{ item }} state=present
  with_items:
      - tmux
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Install package
  dnf: name={{ item }} state=present
  with_items:
      - tmux
  become: true
  when: ansible_distribution == 'Fedora'
