---
- name: Install package
  ansible.builtin.apt:
    lname: "{{ item }}"
    state: present
  with_items:
      - tmux
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Install package
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: "present"
  with_items:
      - tmux
  become: true
  when: ansible_distribution == 'Fedora'
