---

- shell: "echo $HOME"
  register: HOME_PATH_RESULT

- set_fact:
    HOME_PATH: "{{ HOME_PATH_RESULT.stdout }}"

- shell: "lsb_release -c|awk '{print $2}'"
  register: UBUNTU_VERSION_RESULT
  when: ansible_distribution == 'Ubuntu'

- set_fact:
    UBUNTU_VERSION: "{{ UBUNTU_VERSION_RESULT.stdout }}"
  when: ansible_distribution == 'Ubuntu'

- path_generator:
  register: stdout

- set_fact: EXTRA_PATH={{ stdout.ENV_PATH }}
