---

- name: clone c9sdk
  git: repo="git://github.com/c9/core.git"
       dest="~/c9sdk"

- name: Install packages
  apt: name={{ item }} state=present
  with_items:
   - git
   - curl
   - wget
   - build-essential
   - python2.7
   - nodejs-legacy

  become: true
  when: ansible_os_family == 'Debian' and programming == true

- name: build sdk
  shell: "./scripts/install-sdk.sh"
  args:
    chdir: "~/c9sdk"
