---
- name: Create nvim config directory
  ansible.builtin.file:
    path: "~/.config/nvim"
    state: directory
    mode: '0750'

- name: Copy nvim config files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "~/.config/nvim/{{ item }}"
    mode: '0640'
  with_items:
    - init.lua
    - nvim.vim

- name: Copy e-ink theme module
  ansible.builtin.copy:
    src: lua/eink_theme.lua
    dest: ~/.config/nvim/lua/eink_theme.lua
    mode: '0640'

- name: Copy LSP configurations
  ansible.builtin.copy:
    src: lsp
    dest: ~/.config/nvim/
    mode: '0640'
    directory_mode: '0750'

- name: Create efm config directory
  ansible.builtin.file:
    path: "~/.config/efm-langserver/"
    state: directory
    recurse: true

- name: Copy efm config
  ansible.builtin.copy:
    src: efm.yaml
    dest: ~/.config/efm-langserver/config.yaml
    mode: '0640'

- name: Create stylua config
  ansible.builtin.file:
    path: "~/.config/nvim/.stylua.toml"
    state: touch
    mode: '0640'
