---
- name: Download appimage
  get_url:
    url: https://github.com/neovim/neovim/releases/download/stable/nvim.appimage
    dest: /opt/nvim.appimage
    mode: 0755
  become: true

- name: Extract appimage
  command: /opt/nvim.appimage --appimage-extract
  args:
    chdir: /opt/
  become: true

- name: Remove /opt/neovim
  file:
    path: /opt/neovim
    state: absent
  become: true

- name: Move squashfs-root neovim
  command: mv squashfs-root neovim
  args:
    chdir: /opt/
  become: true

- name: Change the permission of files
  command: find /opt/neovim/ -type d -exec chmod go+rx {} \;
  args:
    chdir: /opt/neovim
  become: true

- name: Link nvim
  file:
    path: /usr/bin/nvim
    src: /opt/neovim/AppRun
    state: link
  become: true
